In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('imputed_dataset2.csv')

In [ ]:
df.head()

# Fix Lake Names

In [170]:
pd.set_option("display.max_colwidth", None)

pattern = r"[^A-Za-z\s,áéíóúñüäýãôõâÉè()/&-.']"

df_symbols = df[df['Lake Name'].str.contains(pattern, regex=True, na=False)]

print(df_symbols[['Lake Name']].drop_duplicates().head(50))

df['Lake Name'] = df['Lake Name'].replace({
    "Ganga River  Bijnor": "Ganga River, Bijnor",
    "Ganga River  Kanpur": "Ganga River, Kanpur",
    "Ganga River  Varanasi": "Ganga River, Varanasi",
    "Ganga River  Allahabad": "Ganga River, Allahabad",
    "Ganga River  Patna": "Ganga River, Patna",
    "Ganga River  Bhagalpur": "Ganga River, Bhagalpur",
    "Ganga River  Kolkata": "Ganga River, Kolkata",
    "Ganga River  Diamond Harbour": "Ganga River, Diamond Harbour",
    "Ganga River  Narora": "Ganga River, Narora",
    "Ganga River  Farrukhabad": "Ganga River, Farrukhabad",
    "Ganga River  Kanpur": "Ganga River, Kanpur",
    "Ganga River  Varanasi": "Ganga River, Varanasi",
    "Ganga River  Prayagraj (Allahabad)": "Ganga River, Prayagraj (Allahabad)",
    "Ganga River  Varanasi / Prayagraj": "Ganga River, Varanasi / Prayagraj",
    "Padma River  Bheramara (Kushtia)": "Padma River, Bheramara (Kushtia)",
    "Brahmaputra River  Guwahati / Kamrup stretches": "Brahmaputra River, Guwahati / Kamrup stretches",
    "Langueyú stream  Urban reach": "Langueyú stream, Urban reach",
    "Langueyú stream  Suburban reach": "Langueyú stream, Suburban reach",
    "Langueyú stream  Rural reach": "Langueyú stream, Rural reach",
    "Langueyú stream  Industrial reach": "Langueyú stream, Industrial reach",
    "Chilika Lake  Rambha": "Chilika Lake, Rambha",
    "Chilika Lake  Balugaon": "Chilika Lake, Balugaon",
    "Chilika Lake  Barkul": "Chilika Lake, Barkul",
    "Chilika Lake  Satapada": "Chilika Lake, Satapada",
    "Chilika Lake  Kalijai": "Chilika Lake, Kalijai",
    "Chilika Lake  Daringbadi": "Chilika Lake, Daringbadi",
    "Chilika Lake  Chhanabhita": "Chilika Lake, Chhanabhita",
    "Chilika Lake  Nalabana": "Chilika Lake, Nalabana",
    "Chilika Lake  Rambha": "Chilika Lake, Rambha",
    "Ganges River (selected reaches; e.g., Haridwar/Allahabad studies)": "Ganges River",
    "Mekong Delta  freshwater tidal zone (Vietnam)": "Mekong Delta, freshwater tidal zone (Vietnam)",
    "McNutt Creek (tributary, Athens / Oconee drainage)  wild records": "McNutt Creek",
    "Chalakudy River , Puliyarkutti 8th bridge": "Chalakudy River, Puliyarkutti 8th bridge",
    "Songhua River (basin-wide)": "Songhua River",
    "Rupnarayan River (Purba Medinipur, West Bengal)  sampling stations A/B/C": "Rupnarayan River (Purba Medinipur, West Bengal)",
    "Kshipra River (Ujjain, Madhya Pradesh)  Ujjain stretch": "Kshipra River (Ujjain, Madhya Pradesh)",
    "Chilika Lake  Rambha": "Chilika Lake, Rambha",
    "Danube  Garla Mare (S1, Romania)": "Danube, Garla Mare (S1, Romania)",
    "Danube  Bogdan Secian (S3)": "Danube, Bogdan Secian (S3)",
    "Danube  Belene (S7)": "Danube, Belene (S7)",
    "Danube  Vardim (S8)": "Danube, Vardim (S8)",
    "Danube  Iantra (S9)": "Danube, Iantra (S9)",
    "Danube  Kosui (S11)": "Danube, Kosui (S11)",
    "Lake Balaton (Hungary)  (specific sites across lake)": "Lake Balaton (Hungary)",
    "Coppename River Basin, Suriname**": "Coppename River Basin, Suriname",
    "Chilika Lake  Rambha ": "Chilika Lake, Rambha",
    "Solimões ": "Solimões River",
    "Solimões / Middle Amazon (Mamirauá / Mamirauá reserve area)": "Solimões / Middle Amazon (Mamirauá)",
    "Cape Fear River Basin, NC (1999)": "Cape Fear River Basin, NC",
    "Como Lake, St. Paul, MN (2017)": "Como Lake, St. Paul, MN",
    "Arkansas Ponds (2010 Study)": "Arkansas Ponds",
    "Danube River (Romania, km 169197)": "Danube River (Romania)",
    "Lake E?irdir, Turkey": "Lake Egirdir",
    "River Chvalinský, Czech Republic": "River Chvalsinsky, Czech Republic",
    "Saint Clair River system (connects Lakes HuronErie)": "Saint Clair River system",
    "Lake D?bie, Poland": "Lake Dabie, Poland",
    "Chenango River (NY, USA) 11.9": "Chenango River (NY, USA)",
    "Chenango River (NY, USA) 7.0": "Chenango River (NY, USA)",
    "River So?a, Slovenia": "River Soca, Slovenia",
    "E?irdir Lake, Turkey": "Egirdir Lake, Turkey",
    "Karata? Lake, Turkey": "Karatas Lake, Turkey",
    "Bistri?a-N?s?ud, Romania (trout farms)": "Bistrita-Nasaud, Romania (trout farms)",
    "Deer 1 Lake, WA": "Deer Lake, WA",
    "So?a River (Slovenia)": "Soca River (Slovenia)",
    "QuAppelle System, Canada (e.g. Buffalo Pound Lake)": "Qu'Appelle System, Canada",
    "Laguna de Bay (Philippines)  fry study": "Laguna de Bay",
    "River Vidå, Denmark": "River Vida, Denmark",
    "?elik Lake, Ad?yaman, Turkey": "Celik Lake, Adiyaman, Turkey",
    "E?lenhoca Reservoir, Turkey": "Eglenhoca Reservoir, Turkey",
    "Lake Malawi  Southeast Arm (Cage site, Maldeco)": "Lake Malawi, Southeast Arm (Cage site, Maldeco)",
    "Lake Malawi  Southeast Arm (Non-cage Southeast station)": "Lake Malawi, Southeast Arm (Non-cage Southeast station)",
    "Lake Malawi  Southeast Arm (Non-cage Northwest station)": "Lake Malawi, Southeast Arm (Non-cage Northwest station)",
    "Río Tecolutla  Gutiérrez Zamora": "Río Tecolutla, Gutiérrez Zamora",
    "Río Tecolutla  El Espinal": "Río Tecolutla, El Espinal",
    "Mekong River  upper & middle reaches (first records reported)": "Mekong River, upper & middle reaches",
    "Study habitat water (lab/experimental context)  unspecified": "Study habitat water (lab/experimental context)",
    "Zhujiang / Pearl River system (Guangdong; Beijiang tributary etc.)  sites with occurrences": "Zhujiang / Pearl River system (Guangdong)",
    "San Francisco BayDelta (general)": "San Francisco Bay Delta",
    "Tributary 3 to Surprise Lake": "Surprise Lake",
    "Upper Mississippi River, Pool 8 (La Crosse / Pool 8 area)": "Upper Mississippi River",
    "Upper Mississippi River Pool 8 (La Crosse area)": "Upper Mississippi River",
    "Lake Tanganyika  Kigoma Bay (Tanzania)": "Lake Tanganyika, Kigoma Bay (Tanzania)",
    "Upper Mississippi River Pool 8, La Crosse area, USA": "Upper Mississippi River",
    "Harris Chain of Lakes (representative: Lake Apopka / HCOL), USA": "Lake Apopka, USA",
    "Caloosahatchee River estuary (S-79 / SW Florida)": "Caloosahatchee River estuary (S 79)",
    "Caloosahatchee River estuary (S 79)": "Caloosahatchee River estuary (S79)",
    "RazimSinoe complex (Romania)": "Razim-Sinoe complex (Romania)",
    "PeaceAthabasca Delta, Canada": "Peace-Athabasca Delta, Canada",
    "Ébrié Lagoon, Côte dIvoire": "Ebrié Lagoon",
    "Chao Phraya River (BangkokAyutthaya reach)": "Chao Phraya River (Bangkok Ayutthaya reach)",
    "Mae Klong River (KanchanaburiSamut Songkhram)": "Mae Klong River (Kanchanaburi Samut Songkhram)",
    "Susquehanna River  SUSQ 37.5": "Susquehanna River",
    "Hudson River  Haverstraw Bay": "Hudson River, Haverstraw Bay",
    "Upper Mississippi River  Pool 8": "Upper Mississippi River",
    "Tokyo Bay  inner station": "Tokyo Bay, Inner Station",
    "Sef?d-R?d River system": "Sefid Rud River system",
    "Peat-swamp streams / blackwater habitats  Borneo / Sumatra / Sundaland": "Borneo Swamp Streams",
    "Cahaba River (AL  representative near West Blocton)": "Cahaba River (AL)",
    "Tallapoosa River (AL  Montgomery area / mainstem)": "Tallapoosa River (AL)",
    "Tombigbee River (AL/MS  Demopolis / Columbus stretches)": "Tombigbee River (AL)",
    "Flint River (GA  Albany / lower reaches)": "Flint River (GA)",
    "North Platte River  lower/near North Platte, NE": "North Platte River (NE)",
    "Platte River  North Bend / central Platte": "Platte River (NE)",
    "Mississippi River  St. Louis": "Mississippi River (MO)",
    "Rivière Blanche (Schlcher)": "Rivière Blanche (Schoelcher)",
    "San Salvador  Crescent Pond (Cyprinodon laciniatus)": "San Salvador (Cyprinodon laciniatus)",
    "Lake Tanganyika  Kalemie Bay (Aphyosemion striatum)": "Lake Tanganyika (Aphyosemion striatum)",
    "Okavango Delta  Seasonal Pool (Nothobranchius furzeri)": "Okavango Delta (Nothobranchius furzeri)",
    "Rio de la Plata Basin  Wetland Pool (Austrolebias bellottii)": "Rio de la Plata Basin (Austrolebias bellottii)",
    "Nimbai Stream  Upper Reach": "Nimbai Stream, Upper Reach",
    "Aimasi Stream  Mid Reach": "Aimasi Stream, Mid Reach",
    "Prafi River  Headwaters": "Prafi River, Headwaters",
    "Drysdale River  Main Reach": "Drysdale River, Main Reach",
    "King Edward River  Pool Zone": "King Edward River",
    "Drysdale River  Tributary": "Drysdale River, Tributary",
    "Wooli River  Tick Gate Swamp": "Wooli River",
    "Mahaweli Basin (GampolaGinigathena)": "Mahaweli Basin (Gampola Ginigathena)",
    "Inle Lake  Central Basin": "Inle Lake, Central Basin",
    "Inle Lake  Southern Swamps": "Inle Lake, Southern Swamps",
    "Lake Poso  Central Basin": "Lake Poso, Central Basin",
    "Lake Poso  Northern Shore": "Lake Poso, Northern Shore",
    "Lake Inle  Floating Garden Zone": "Lake Inle, Floating Garden Zone",
    "Lake Poso  Station S-1 (Koburo) - Central Sulawesi Indonesia": "Lake Poso, Station S1 (Koburo)",
    "Lake Poso  Station S-2 (Bo'e) - Central Sulawesi Indonesia": "Lake Poso, Station S2 (Bo'e)",
    "Lake Poso  Station S-3 (Tolambo) - Central Sulawesi Indonesia": "Lake Poso, Station S3 (Tolambo)",
    "Lake Poso  Station S-4 (Peura) - Central Sulawesi Indonesia": "Lake Poso, Station S4 (Peura)",
    "Lake Poso  Station S-5 (Tentena) - Central Sulawesi Indonesia": "Lake Poso, Station S5 (Tentena)",
    "MurrayDarling Basin streams (southeastern Australia)": "Murray-Darling Basin streams (southeastern Australia)",
    "South & Southeast Asia  lowland ponds, slow streams, rice paddies": "South & Southeast Asia ponds",
    "Congo River  Yangambi region": "Congo River, Yangambi region",
    "Lake Victoria  Mwanza Gulf (Tanzania)": "Lake Victoria, Mwanza Gulf (Tanzania)",
    "Derwent headwaters, Tasmania (Australia)": "Derwent headwaters, Tasmania (Australia)",
    "MurrayDarling River": "Murray Darling River",
    "Barwon River (MurrayDarling Basin), Australia": "Barwon River (Murray Darling Basin), Australia",
    "Río Usumacinta (MexicoGuatemala)": "Río Usumacinta (Mexico Guatemala)",
    "Volta River drainage (shallow rocky/riverine habitats)": "Volta River (Ghana)",
    "Derwent headwaters, Tasmania (Australia)": "Derwent headwaters, Tasmania (Australia)",
    "Volta River drainage (shallow rocky/riverine habitats)": "Volta River (Ghana)",
    "Lake Chapala (LermaChapala basin, Mexico)": "Lake Chapala (Lerma Chapala basin, Mexico)",
    "Derwent headwaters, Tasmania (Australia////0": "Derwent headwaters, Tasmania (Australia)",
    "Volta River drainage (shallow rocky/riverine habitats)  Volta River (Ghana)": "Volta River (Ghana)",
    "Lake Geneva / Lac Léman (CIPEL monitoring, central lake)": "Lake Geneva / Lac Leman"
})

                                     Lake Name
112   Chalakudy River, Puliyarkutti 8th bridge
142                 Danube, Bogdan Secian (S3)
143                        Danube, Belene (S7)
144                        Danube, Vardim (S8)
145                        Danube, Iantra (S9)
146                        Danube, Kosui (S11)
161                    Lake Väddöviken, Sweden
841                  Laguna de Bay (Station 2)
842                  Laguna de Bay (Station 3)
843                Manurigao River (Station 2)
844                Manurigao River (Station 3)
1416             Tributary 4 (Waterfall Creek)
1527        Caloosahatchee River estuary (S79)
1554                          Lake 223, Canada
2261            Lake Poso, Station S1 (Koburo)
2262              Lake Poso, Station S2 (Bo'e)
2263           Lake Poso, Station S3 (Tolambo)
2264             Lake Poso, Station S4 (Peura)
2265           Lake Poso, Station S5 (Tentena)

In [171]:
df.head()

,Fish ID,Species,Common Name,Lake Name,Kingdom,Phylum,Class,Order,Family,Genus,...,WB_Salinity_min,WB_Salinity_max,WB_Dissolved Oxygen (mg/L)_min,WB_Dissolved Oxygen (mg/L)_max,WB_Biochemical Oxygen Demand (mg/L)_min,WB_Biochemical Oxygen Demand (mg/L)_max,WB_Turbidity (NTU)_min,WB_Turbidity (NTU)_max,WB_Temperature_min,WB_Temperature_max
0,F0001,Copella arnoldi,Splash tetra,Amazon Basin,Animalia,Chordata,Actinopterygii,Characiformes,Lebiasinidae,Copella,...,0.0,0.0,5.5,5.5,2.0,2.0,4.0,4.0,27.0,27.0
1,F0001,Copella arnoldi,Splash tetra,Demerara River Wismar,Animalia,Chordata,Actinopterygii,Characiformes,Lebiasinidae,Copella,...,0.0,0.0,6.0,6.0,3.0,3.0,6.0,6.0,27.0,27.0
2,F0001,Copella arnoldi,Splash tetra,Yarakita River,Animalia,Chordata,Actinopterygii,Characiformes,Lebiasinidae,Copella,...,0.0,0.0,5.0,5.0,2.0,2.0,3.0,3.0,26.5,26.5
3,F0001,Copella arnoldi,Splash tetra,Arauau River,Animalia,Chordata,Actinopterygii,Characiformes,Lebiasinidae,Copella,...,0.0,0.0,5.2,5.2,2.0,2.0,4.0,4.0,27.0,27.0
4,F0001,Copella arnoldi,Splash tetra,"Kurupung River, Upper Mazaruni District",Animalia,Chordata,Actinopterygii,Characiformes,Lebiasinidae,Copella,...,0.0,0.0,4.5,4.5,4.0,4.0,20.0,20.0,26.0,26.0

In [172]:
df.to_csv('finalized_lake_names_v2.csv', index=False)

# Standardizing Column Names

In [176]:
print(df.columns.tolist())

['Fish ID', 'Species', 'Common Name', 'Lake Name', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Statues', 'FeedingType', 'Tmax', 'Wmax', 'Lmax', 'TempPref_min', 'TempPref_max', 'TempRange', 'MeanFecundity', 'MinFecundity', 'MaxFecundity', 'Trophic Level Estimate', 'Trophic Level', 'WB_pH_min', 'WB_pH_max', 'WB_Salinity_min', 'WB_Salinity_max', 'WB_Dissolved Oxygen (mg/L)_min', 'WB_Dissolved Oxygen (mg/L)_max', 'WB_Biochemical Oxygen Demand (mg/L)_min', 'WB_Biochemical Oxygen Demand (mg/L)_max', 'WB_Turbidity (NTU)_min', 'WB_Turbidity (NTU)_max', 'WB_Temperature_min', 'WB_Temperature_max']

In [177]:
import re

def to_snake_case(col):
    # 1. Replace spaces and special chars with underscore
    col = re.sub(r'[^0-9a-zA-Z]+', '_', col)
    # 2. Lowercase
    col = col.lower()
    # 3. Remove leading/trailing underscores
    col = col.strip('_')
    return col

df.columns = [to_snake_case(c) for c in df.columns]

print(df.columns.tolist())

['fish_id', 'species', 'common_name', 'lake_name', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'statues', 'feedingtype', 'tmax', 'wmax', 'lmax', 'temppref_min', 'temppref_max', 'temprange', 'meanfecundity', 'minfecundity', 'maxfecundity', 'trophic_level_estimate', 'trophic_level', 'wb_ph_min', 'wb_ph_max', 'wb_salinity_min', 'wb_salinity_max', 'wb_dissolved_oxygen_mg_l_min', 'wb_dissolved_oxygen_mg_l_max', 'wb_biochemical_oxygen_demand_mg_l_min', 'wb_biochemical_oxygen_demand_mg_l_max', 'wb_turbidity_ntu_min', 'wb_turbidity_ntu_max', 'wb_temperature_min', 'wb_temperature_max']

In [190]:
df = df.rename(columns={
    "lake_name": "waterbody_name",
    "feedingtype": "feeding_type",
    "statues": "status",
    "wmax": "weight_max",
    "tmax": "temp_max",
    "lmax": "length_max",
    "temppref_min": "temp_pref_min",
    "temppref_max": "temp_pref_max",
    "temprange": "temp_range",
    "meanfecundity": "fecundity_mean",
    "maxfecundity": "fecundity_max",
    "minfecundity": "fecundity_min",
    "wb_dissolved_oxygen_mg_l_min": "wb_do_min",
    "wb_dissolved_oxygen_mg_l_max": "wb_do_max",
    "wb_biochemical_oxygen_demand_mg_l_min": "wb_bod_min",
    "wb_biochemical_oxygen_demand_mg_l_max": "wb_bod_max",
    "wb_turbidity_ntu_min": "wb_turbidity_min",
    "wb_turbidity_ntu_max": "wb_turbidity_max",
    "wb_temperature_min": "wb_temp_min",
    "wb_temperature_max": "wb_temp_max"
})

In [191]:
print(df.columns.tolist())

['fish_id', 'species', 'common_name', 'waterbody_name', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'status', 'feeding_type', 'temp_max', 'weight_max', 'length_max', 'temp_pref_min', 'temp_pref_max', 'temp_range', 'fecundity_mean', 'fecundity_min', 'fecundity_max', 'trophic_level_estimate', 'trophic_level', 'wb_ph_min', 'wb_ph_max', 'wb_salinity_min', 'wb_salinity_max', 'wb_do_min', 'wb_do_max', 'wb_bod_min', 'wb_bod_max', 'wb_turbidity_min', 'wb_turbidity_max', 'wb_temp_min', 'wb_temp_max']

In [192]:
df.to_csv('standardized_dataset.csv', index=False)

In [ ]:
df = pd.read_csv('standardized_dataset.csv')
df